FROM cybertec/pgwatch2-postgres:1.10

RUN mkdir /grafana-extra-plugins
ADD https://storage.googleapis.com/plugins-community/savantly-heatmap-panel/release/0.2.1/savantly-heatmap-panel-0.2.1.zip /grafana-extra-plugins/
